services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: main-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=14d'
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - monitoring_net

  loki:
    image: grafana/loki:3.0.0
    container_name: main-loki
    restart: unless-stopped
    ports:
      - "0.0.0.0:3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml # Mount the clean config here
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:11.0.0
    container_name: main-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "0.0.0.0:3000:3000" # Open to public for dashboard access
    networks:
      - monitoring_net

volumes:
  prometheus-data:
  loki-data:
  grafana-data:

networks:
  monitoring_net:
    driver: bridge