...


    location /metrics/vps {
        auth_basic           "Authentication Required";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        proxy_pass           http://172.17.0.1:9100/metrics;
        proxy_set_header     Host $host;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header     X-Forwarded-Proto $scheme;
    }

    location /metrics/containers {
        auth_basic           "Authentication Required";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        proxy_pass           http://172.17.0.1:8080/metrics;
        proxy_set_header     Host $host;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header     X-Forwarded-Proto $scheme;
    }
...